roll_distance: 30
roll_cap: 99
show_distance: 30
range_distance: 100
sit_blocks:
  #SLABS
  - OAK_SLAB
  - SPRUCE_SLAB
  - BIRCH_SLAB
  - JUNGLE_SLAB
  - ACACIA_SLAB
  - DARK_OAK_SLAB
  - STONE_SLAB
  - SANDSTONE_SLAB
  - PETRIFIED_OAK_SLAB
  - COBBLESTONE_SLAB
  - BRICK_SLAB
  - STONE_BRICK_SLAB
  - NETHER_BRICK_SLAB
  - QUARTZ_SLAB
  - RED_SANDSTONE_SLAB
  - PURPUR_SLAB
  - PRISMARINE_SLAB
  - PRISMARINE_BRICK_SLAB
  - DARK_PRISMARINE_SLAB
  #STAIRS
  - OAK_STAIRS
  - SPRUCE_STAIRS
  - BIRCH_STAIRS
  - JUNGLE_STAIRS
  - ACACIA_STAIRS
  - DARK_OAK_STAIRS
  - SANDSTONE_STAIRS
  - COBBLESTONE_STAIRS
  - BRICK_STAIRS
  - STONE_BRICK_STAIRS
  - NETHER_BRICK_STAIRS
  - QUARTZ_STAIRS
  - RED_SANDSTONE_STAIRS
  - PURPUR_STAIRS
  - PRISMARINE_STAIRS
  - PRISMARINE_BRICK_STAIRS
  - DARK_PRISMARINE_STAIRS